name: build toolchain

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Build toolchain
        run: |
          make toolchain/build
          cd toolchain-mipsel/toolchain-4.4.x
          tar cJf ../mipsel-linux-uclibc-gcc10.tar.xz *
      - uses: actions/upload-artifact@main
        with:
          name: toolchain
          path: toolchain-mipsel/mipsel-linux-uclibc-gcc10.tar.xz
      - uses: ncipollo/release-action@main
        with:
          token: ${{ github.token }}
          tag: toolchain
          artifacts: toolchain-mipsel/mipsel-linux-uclibc-gcc10.tar.xz
          allowUpdates: true
